# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Type ======================================================================
  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.38.4
    hooks:
      - id: basedpyright
  # Lint ======================================================================
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.8
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --show-fixes]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.7.4"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]
  # Dependencies ==============================================================
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.26
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--output-file=requirements.txt", "--no-dev", "--quiet"]
  # Misc. =====================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [html, svg]
      - id: trailing-whitespace
  # - repo: https://github.com/codespell-project/codespell
  #   rev: "v2.4.1"
  #   hooks:
  #     - id: codespell
  #       additional_dependencies:
  #         - tomli; python_version<'3.11'
