# For now, allow errors and warnings
# Change once documentation is complete
strict: false

extra_css:
  - _static/css/main.css
  #- _static/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css

docs_dir: documentation

site_name: Bayesian Confusion Matrices
site_url: https://github.com/ioverho/bayes_conf_mat
# TODO: add a description
site_description: ""
site_author: Ivo Verhoeven
use_directory_urls: false

repo_url: https://github.com/ioverho/bayes_conf_mat
repo_name: ioverho/bayes_conf_mat

copyright: Copyright &copy; 2025 Ivo Verhoeven

nav:
  - index.md
  - Getting Started:
      - Getting Started/01_estimating_uncertainty.ipynb
      - Getting Started/02_comparing_experiments.ipynb
      - Getting Started/03_aggregating_experiments.ipynb
      - Getting Started/04_interfacing_with_the_filesystem.ipynb
  - How-To:
      - How To Guides/index.md
      - How To Guides/extending_the_library.md
      #- How To Guides/configuration.md
      #- How To Guides/metric_syntax.md
      #- How To Guides/extending_the_library/implementing_metrics_and_aggregations.md
  - Reference:
      #- References/ExperimentManager.md
      #- References/Experiment.md
      - Reference/index.md
      - Reference/Study.md
      - Metrics:
          - Reference/Metrics/index.md
          - Reference/Metrics/Metrics.md
          - Reference/Metrics/Averaging.md
      - Experiment Aggregation:
          - Reference/Experiment Aggregation/index.md
          - Reference/Experiment Aggregation/heterogeneity.md
      - Reference/IO.md
  - Explanation:
      - "Explanation/index.md"
      - "Explanation/generating_confusion_matrices.md"

theme:
  name: material
  language: en
  # Project logo, top-left
  # TODO: get a nice logo
  logo: _static/logo.png
  favicon: _static/logo.png
  icon:
    # GitHub logo, top-right
    repo: fontawesome/brands/github
  features:
    # Footnotes with tooltip hover
    # https://squidfunk.github.io/mkdocs-material/reference/footnotes
    - content.footnote.tooltips
    # Tooltips for elements
    # https://squidfunk.github.io/mkdocs-material/reference/tooltips/#improved-tooltips
    - content.tooltips
    # Code block copy and line selection
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
    - content.code.copy
    - content.code.select
    # ==========================================================================
    # Navigation
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    # ==========================================================================
    # Loading without flicker
    - navigation.instant
    # Progress bar for slow connections
    - navigation.instant.progress
    # Add navigation headers to the top
    - navigation.tabs
    - navigation.tabs.sticky
    # Section pages
    - navigation.indexes
    # URL matches active anchor
    - navigation.tracking
    # Only keep the first page of a section
    - navigation.prune
    # ==========================================================================
    # Table of content
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents
    # ==========================================================================
    - toc.follow
    # Back to top buttons
    - navigation.top
    # ==========================================================================
    # Search
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
    # ==========================================================================
    #- search
    # Suggestions
    - search.suggest
    # ==========================================================================
    # Misc
    # ==========================================================================
    - navigation.footer
  palette:
    # TODO: come up with own colour palette
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    # Light mode / dark mode
    - scheme: light
      primary: white
      accent: indigo
      toggle:
        icon: material/circle-half-full
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/circle-half-full
        name: Switch to light mode

plugins:
  # Search bar
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  - search
  - privacy
  - social
  - mkdocs-jupyter:
      #no_input: True
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ./src/
          options:
            # Do not add source code as block
            show_source: false
            heading_level: 2
            show_root_heading: true
            show_root_members_full_path: false
            # Don't show the entire path of a class
            show_root_full_path: false
            # Add symbol types, like Github
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            docstring_section_style: table # table | list | spacy
            # Order by code, not name
            members_order: source
            # Try to keep annotations limited
            annotations_path: brief
            # Add categories to docstrings
            group_by_category: true
            show_category_heading: true
            extensions:
              # Allows importing documentation from parent class
              - griffe_inherited_docstrings
  #- git-revision-date-localized:
  #    enable_creation_date: false
  #    type: date

markdown_extensions:
  # Callouts
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  # TOC handling
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
  - toc:
      permalink: "#"
      toc_depth: 4
  # Footnotes with tooltip hover
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes
  - footnotes
  # MathJax
  # https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-mkdocsyml
  - pymdownx.arithmatex:
      generic: true
  # Better bold and italics detection
  - pymdownx.betterem
  # Details
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details
  - pymdownx.details
  # Fancy code blocks
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Allows integrating files into document
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=snipp#snippets
  - pymdownx.snippets
  # Nested callouts
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences
  - pymdownx.superfences

extra_javascript:
  # MathJax
  # https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-mkdocsyml
  #- _static/mathjax.js
  #- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  #- https://polyfill.io/v3/polyfill.min.js?features=es6
  #- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  #- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - _static/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
