[tool.poetry]
name = "bayes-conf-mat"
version = "0.0.1"
description = "A Bayesian treatment of the confusion matrix, enabling uncertainty estimation and experiment aggregation."
authors = ["Ivo Verhoeven <i.o.verhoeven2@uva.nl>"]
license = "MIT"
readme = "README.md"
packages = [{include = "bayes_conf_mat"}]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.20"
jax = "^0.4"
jaxtyping = "^0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
