[project]
name = "bayes_conf_mat"
version = "0.0.1"
description = "An easy, efficient package to derive uncertainty estimates, perform simple hypothesis tests and aggregate experiments from confusion matrices."
authors = [
  { name = "Ivo Verhoeven", email = "ioverho@mailbox.org" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.8"
dependencies = [
  "requests>2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
"Homepage" = "https://github.com/pypa/bayes_conf_mat"

[tool]
