name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'pyproject.toml'
      - 'documentation/**'
      - 'mkdocs.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
      - 'pyproject.toml'
      - 'documentation/**'
      - 'mkdocs.yaml'

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  documentation:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.13"
          python-version: "3.11"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build documentation
        run: uv run --dev mkdocs gh-deploy --clean --site-dir "./site" --force
